version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - debezium-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9093
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    entrypoint: ["sh", "-c", "/scripts/wait-for-it.sh zookeeper:2181 -- /bin/bash /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"]
    volumes:
      - ./scripts:/scripts
    networks:
      - debezium-net

  kafka-setup:
    image: wurstmeister/kafka:latest
    container_name: kafka-setup
    depends_on:
      - kafka
    entrypoint: >
      /bin/bash -c "
      /opt/kafka/bin/kafka-topics.sh --create --topic my-connect-configs --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --config cleanup.policy=compact &&
      /opt/kafka/bin/kafka-topics.sh --create --topic my-connect-offsets --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --config cleanup.policy=compact &&
      /opt/kafka/bin/kafka-topics.sh --create --topic my-connect-status --bootstrap-server kafka:9093 --replication-factor 1 --partitions 1 --config cleanup.policy=compact"
    networks:
      - debezium-net

  debezium:
    image: debezium/connect:1.9
    container_name: debezium-connector
    environment:
      - BOOTSTRAP_SERVERS=kafka:9093
      - CONNECT_REST_PORT=8083
      - CONNECT_GROUP_ID=debezium
      - CONNECT_CONFIG_STORAGE_TOPIC=my-connect-configs
      - CONNECT_OFFSET_STORAGE_TOPIC=my-connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=my-connect-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.storage.StringConverter
      - CONNECT_VALUE_CONVERTER=io.debezium.converters.AvroConverter
    depends_on:
      - kafka-setup
    ports:
      - "8083:8083"
    networks:
      - debezium-net

networks:
  debezium-net:
    driver: bridge
